FROM mcr.microsoft.com/dotnet/sdk:10.0.302 AS build
WORKDIR /src

COPY ["global.json", "."]
COPY ["Directory.Build.props", "."]
COPY ["BannedSymbols.txt", "."]
COPY [".editorconfig", "."]
COPY ["src/symphony-test-1.DatabaseMigrations/symphony-test-1.DatabaseMigrations.csproj", "src/symphony-test-1.DatabaseMigrations/"]
COPY ["src/symphony-test-1.DatabaseMigrations/packages.lock.json", "src/symphony-test-1.DatabaseMigrations/"]
RUN dotnet restore "src/symphony-test-1.DatabaseMigrations/symphony-test-1.DatabaseMigrations.csproj" --locked-mode

COPY . .
WORKDIR "/src/src/symphony-test-1.DatabaseMigrations"
RUN dotnet publish "symphony-test-1.DatabaseMigrations.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/runtime:10.0.10 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "SymphonyTest1.DatabaseMigrations.dll"]
