<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SymphonyTest1.Web</AssemblyName>
    <RootNamespace>SymphonyTest1.Web</RootNamespace>
    <MetricsSupport>true</MetricsSupport>
    <EventSourceSupport>true</EventSourceSupport>
    <HttpActivityPropagationSupport>true</HttpActivityPropagationSupport>
  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Net.Http.EnableActivityPropagation">
      <Value>true</Value>
    </RuntimeHostConfigurationOption>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.10" />
    <PackageReference Include="MudBlazor" Version="9.7.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\symphony-test-1.ClientServiceDefaults\symphony-test-1.ClientServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SymphonyTest1.WebTests" />
  </ItemGroup>

</Project>
